# Generated by Django 2.0.3 on 2019-12-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_wizard', '0016_auto_20191207_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='eduwizard',
            name='date_ended',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eduwizard',
            name='date_started',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emloymentwizard',
            name='date_ended',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emloymentwizard',
            name='date_started',
            field=models.DateField(auto_now=True),
        ),
    ]
