# Generated by Django 2.0.3 on 2019-12-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_wizard', '0017_auto_20191213_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='payment',
            field=models.IntegerField(default=12345),
        ),
    ]
