# Generated by Django 2.0.3 on 2019-09-26 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_wizard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='freeprofilewizard',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freelancerID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emloymentwizard',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_wizard.FreeProfileWizard'),
        ),
        migrations.AddField(
            model_name='eduwizard',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeID', to='profile_wizard.FreeProfileWizard'),
        ),
        migrations.AddField(
            model_name='educationwizard',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancerID', to='profile_wizard.FreeProfileWizard'),
        ),
    ]
