# Generated by Django 2.0.3 on 2019-10-31 13:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_wizard', '0003_auto_20191031_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeprofilewizard',
            name='profile_image',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='media/photos'),
        ),
    ]
