# Generated by Django 2.0.3 on 2019-11-03 21:14

import django.core.files.storage
from django.db import migrations, models
import phone_field.models
import profile_wizard.utils


class Migration(migrations.Migration):

    dependencies = [
        ('profile_wizard', '0004_auto_20191031_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeprofilewizard',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='freeprofilewizard',
            name='profile_image',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=profile_wizard.utils.get_image_path),
        ),
    ]
