# Generated by Django 2.0.3 on 2019-11-03 22:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profile_wizard', '0005_auto_20191104_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeprofilewizard',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
