# Generated by Django 2.0.3 on 2019-11-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_wizard', '0009_auto_20191120_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
