# Generated by Django 2.0.3 on 2019-11-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_wizard', '0011_auto_20191123_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='deadline',
            field=models.DateField(auto_now=True),
        ),
    ]
