# Generated by Django 2.0.3 on 2019-12-06 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_wizard', '0013_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(default='empty', max_length=64)),
                ('prof_title', models.CharField(blank=True, max_length=64, null=True)),
                ('prof_overview', models.TextField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, choices=[('More Then 30hr', 'More Then 30Hr/Week'), ('Less Then 30hr', 'Less Then 30Hr/Week'), ('As Needed', 'As Needed')], max_length=64)),
                ('payment', models.IntegerField(default=12345)),
                ('category_industry', models.CharField(blank=True, choices=[('Accountancy', 'Accountancy'), ('Admin', 'Admin'), ('Agriculture', 'Agriculture'), ('Automotive', 'Automotive'), ('Aviation', 'Aviation'), ('Banking', 'Banking'), ('Construction', 'Construction'), ('Consulting', 'Consulting'), ('Cosmetics', 'Cosmetics'), ('Cyber Security', 'Cyber Security'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('Finance', 'Finance'), ('FMCG', 'FMCG'), ('General Trading', 'General Trading'), ('Government', 'Government'), ('Healthcare', 'Healthcare'), ('Hospitality', 'Hospitality'), ('HR', 'HR'), ('Insurance', 'Insurance'), ('IT', 'IT'), ('Law', 'Law'), ('Logistics', 'Logistics'), ('Manufacturing', 'Manufacturing'), ('Marketing', 'Marketing'), ('Media', 'Media'), ('Non-Profit', 'Non-Profit'), ('Oil & Gas', 'Oil & Gas'), ('Personal/Domestic Care', 'Personal/Domestic Care'), ('Publishing', 'Publishing'), ('Real Estate', 'Real Estate'), ('Retail', 'Retail'), ('Security', 'Security'), ('Shipping', 'Shipping'), ('Telecom', 'Telecom'), ('Translation', 'Translation'), ('Utilities', 'Utilities')], max_length=64)),
                ('language_compatancy', models.CharField(blank=True, choices=[('None', 'Select your profesionality'), ('Basic', 'Basic: I write in this language decently'), ('Conversational', 'Conversational: I write and speak this language well'), ('Fluent', 'Fluent: I write and speak this language almost perfectly'), ('Native or Bilingual', 'Native: I write and speak this language perfectly, including colloquialisms')], max_length=255)),
                ('address_1', models.CharField(default='unknown', max_length=128, verbose_name='address')),
                ('address_2', models.CharField(blank=True, default='unknown', max_length=128, verbose_name="address cont'd")),
                ('city', models.CharField(default='unknown', max_length=64, verbose_name='city')),
                ('zip_code', models.CharField(default=12345, max_length=5, verbose_name='zip code')),
                ('country', models.CharField(default='unknown', max_length=128, verbose_name='country')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EmployeeID', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
