# Generated by Django 2.0.3 on 2019-12-06 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_wizard', '0014_employeeprofilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationwizard',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EmployeeID', to='profile_wizard.EmployeeProfileModel'),
        ),
        migrations.AlterField(
            model_name='eduwizard',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeID', to='profile_wizard.EmployeeProfileModel'),
        ),
        migrations.AlterField(
            model_name='emloymentwizard',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_wizard.EmployeeProfileModel'),
        ),
    ]
