# Generated by Django 2.0.3 on 2019-12-07 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_wizard', '0015_auto_20191206_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emloymentwizard',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProfileID', to='profile_wizard.EmployeeProfileModel'),
        ),
    ]
