# Generated by Django 2.0.3 on 2019-12-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_wizard', '0016_auto_20191207_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofilemodel',
            name='phone',
            field=models.CharField(default='unknown', max_length=128, verbose_name='phone'),
        ),
    ]
