# Generated by Django 2.0.3 on 2019-12-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_wizard', '0018_auto_20191215_0250'),


    ]

    operations = [
        migrations.AddField(
            model_name='emloymentwizard',
            name='month_ended',
            field=models.CharField(blank=True, choices=[('', 'Month'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=64),
        ),
    ]
