# Generated by Django 2.0.3 on 2019-12-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_wizard', '0019_emloymentwizard_month_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofilemodel',
            name='status',
            field=models.CharField(choices=[('Freelancer', 'Freelancer'), ('Fulltime', 'Fulltime')], default='empty', max_length=64),
        ),
    ]
