# Generated by Django 2.0.3 on 2019-12-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [

        ('jobapply', '0002_jobapply_applier_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapply',
            options={'ordering': ['-id']},
        ),
    ]
