"""
Django settings for jobs project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""



SILENCED_SYSTEM_CHECKS = ["urls.W005"]
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "jobs.settings")
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMP_DIR =  os.path.join(BASE_DIR,'templates')

#print (TEMP_DIR)
STATIC_DIR = os.path.join(BASE_DIR,'static')
MEDIA_DIR = os.path.join(BASE_DIR, 'media')

LOGIN_REDIRECT_URL = 'profiles'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xt$1y^_$s(iwvc!1wq%u#9axmzh-*x%@(j_2mvv(d5661$xhhk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


#git allowed hosts update

ALLOWED_HOSTS = ['*']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'django.contrib.formtools',
    'django_extensions',
    'phone_field',
    'phonenumber_field',
    'paypal.standard.ipn',
    #'users.apps.UsersConfig',
    'dj_pagination',
    'formtools',
    'home',
    'users',
    'profile_wizard',
    'jobapply',
    'django_private_chat',
    'postman',

    'stripe_test',
    'paypal_subscription',


]
AUTH_USER_MODEL = 'users.CustomUser'
SILENCED_SYSTEM_CHEKS = []
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jobs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMP_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.bar',
                'postman.context_processors.inbox',
            ],
        },
    },
]

WSGI_APPLICATION = 'jobs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'



STATICFILES_DIRS = [
    STATIC_DIR,
]
MEDIA_URL = '/media/'
MEDIA_ROOT = MEDIA_DIR
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'gio.sanikidze@gmail.com'
#EMAIL_HOST_PASSWORD = ''

#EMAIL_HOST_USER = 'no-reply@techjobs.awsapps.com'
#EMAIL_HOST_PASSWORD = ''
EMAIL_HOST_PASSWORD = '01011986Xrp'
EMAIL_USE_TLS = True
#HOST_USE_SSL = True

#SRTIPE KEYS
STRIPE_SECRET_KEY = 'sk_test_6XYiLtx2o41HRwkMhg8TrYly00auH05AFW'
STRIPE_PUBLISHABLE_KEY = 'pk_test_u4q4UExS1w124R8uPYLH6Rrb00N5roKoxu'


#EMAIL_BACKEND = 'django_ses.SESBackend'
AWS_ACCESS_KEY_ID ="AKIASUHLKOZTFHTAUHB6"

AWS_SES_REGION_NAME = 'eu-west-1'
AWS_SES_REGION_ENDPOINT = 'email.eu-west-1.amazonaws.com'

PAYPAL_RECEIVER_EMAIL = 'sb-cmhfb616945@business.example.com'

PAYPAL_TEST = True
POSTMAN_AUTO_MODERATE_AS = True
CHAT_WS_SERVER_HOST = 'localhost'
CHAT_WS_SERVER_PORT = 5002
CHAT_WS_SERVER_PROTOCOL = 'ws'




