# Generated by Django 2.0.3 on 2019-12-07 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_wizard', '0016_auto_20191207_2249'),
        ('jobapply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='applier_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='profile_wizard.EmployeeProfileModel'),
        ),
    ]
