# Generated by Django 2.0.3 on 2019-12-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapply', '0003_auto_20191214_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
